language: python
python:
  - "3.6"      # current default Python on Travis CI
install:
  - pip3 install -e .[test]
  - pip3 install -e .
# tests need docker
services:
  - docker
# command to run tests
script:
  - export DOCKER_API_VERSION=1.39 # otherwise we will see errors like https://github.com/kubernetes-sigs/kubespray/issues/6160
  - make test
