language: python
python:
  - "3.6"      # current default Python on Travis CI
install:
  - pip3 install -e .[test]
  - pip3 install -e .
# tests need docker
services:
  - docker
# command to run tests
script:
  - make test
